#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun May 14 07:15:56 2023

@author: joe

Combine Depthify and LayNii Data:
    I just want all of the variables in the same dictionary.
"""

#import nibabel
import os, glob
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import json
import pandas as pd

#Import custom functions
from oriseg_funcs import *

#%% Import data
mainDir = '/Users/joe/Documents/Olman_Lab/OriSeg/code'
#datasets = glob.glob(os.path.join(mainDir, 'roi_data', 'pnr???_??_??_?????.csv'))
laynii_datafiles = ['/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr102_V1_lh_target_laynii.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr102_V1_rh_target_laynii.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr256_V1_lh_target_laynii.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr256_V1_rh_target_laynii.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr328_V1_lh_target_laynii.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr328_V1_rh_target_laynii.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr510_V1_lh_target_laynii.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr510_V1_rh_target_laynii.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr739_V1_lh_target_laynii.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr739_V1_rh_target_laynii.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr756_V1_lh_target_laynii.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr756_V1_rh_target_laynii.csv'
  ]
depthify_datafiles = ['/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr102_V1_lh_target.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr256_V1_lh_target.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr256_V1_rh_target.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr328_V1_lh_target.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr328_V1_rh_target.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr510_V1_lh_target.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr510_V1_rh_target.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr739_V1_lh_target.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr739_V1_rh_target.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr756_V1_lh_target.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr756_V1_rh_target.csv'
  ]
laynii_datafiles.sort()
depthify_datafiles.sort()

laynii_data = {}
for dataset in laynii_datafiles:
    p, f = os.path.split(dataset)
    f, ex = os.path.splitext(f)
    laynii_data[f] = pd.read_csv(dataset, sep=',', index_col=False)
    
depthify_data = {}
for dataset in depthify_datafiles:
    p, f = os.path.split(dataset)
    f, ex = os.path.splitext(f)
    depthify_data[f] = pd.read_csv(dataset, sep=',', index_col=False)
    
laynii_keys = list(laynii_data.keys())
for i in range(len(laynii_keys)):
    laynii_keys[i] = laynii_keys[i][:-7] #remove the "_laynii" label at the end
depthify_keys = list(depthify_data.keys())
common_keys = np.intersect1d(depthify_keys,laynii_keys)
    
all_data = {}
for key in common_keys:
    all_data[key] = pd.concat([laynii_data[key+'_laynii'],depthify_data[key]])