#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@author: cheryl

This code combines work from Cheryl and Joe for creating laminar and surface
profiles from the OriSeg data. This code specifically focuses on the analysis 
of contextual conditions.
"""
#import nibabel
import os, glob
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import json

#Import custom functions
from oriseg_funcs_v3 import *

plt.close('all')
    
fcolor = 'white'#[.125, .125, .125]
lcolor = 'black'##[1., 1., 1.]
savefigs = False #True #if true save all figures
figDir = '/Users/joe/Documents/Olman_Lab/OriSeg/code/figs/'

#%%###########################################################################
#############################################################################
########### Notice that each hemisphere is treated as a dataset
#mainDir = '/home/scat-raid3/data/oriSeg'
mainDir = '/Users/joe/Documents/Olman_Lab/OriSeg/code'
#datasets = glob.glob(os.path.join(mainDir, 'roi_data', 'pnr???_??_??_?????.csv'))
datasets = [#'/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr102_V1_lh_target_laynii.csv',
   #'/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr102_V1_rh_target_laynii.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr256_V1_lh_target_laynii.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr256_V1_rh_target_laynii.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr328_V1_lh_target_laynii.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr328_V1_rh_target_laynii.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr510_V1_lh_target_laynii.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr510_V1_rh_target_laynii.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr739_V1_lh_target_laynii.csv',
   '/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr739_V1_rh_target_laynii.csv',
   #'/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr756_V1_lh_target_laynii.csv',
   #'/Users/joe/Documents/Olman_Lab/OriSeg/code/roi_data/pnr756_V1_rh_target_laynii.csv'
  ]
datasets.sort()

roiRad = 2 #1.
import pandas as pd
all_data = {}
for dataset in datasets:
    p, f = os.path.split(dataset)
    f, ex = os.path.splitext(f)
    all_data[f] = pd.read_csv(dataset, sep=',', index_col=False)

# check and see what the Stria profile looks like in each ROI
nDepths = 8 #10
fig = plt.figure(num=1)
fig.clf()
for iR, label in enumerate(all_data.keys()):
    df = all_data[label]
    
    roi = df[df['scale_uv_dist'] < roiRad]
    roi = roi[roi['scale_uv_dist'] > 0]
    dataDict = makeProfile1D(roi['d'].values,
                             nDepths, #number of depths
                             roi['t1'].values,
                             np.min(roi['d'].values), #min depth value
                             np.max(roi['d'].values), #max depth value
                             True) #Use LayNii values
    
    plt.subplot(int(np.ceil(len(all_data.keys())/2.)), 2, 1 + iR)
    plt.plot(dataDict['profile']['depth'],
             dataDict['profile']['avg'][0])
    plt.title('%s (%d vox)' %(label, len(roi)), fontsize=8)
    
if savefigs:
    fig.savefig(os.path.join(figDir,'t1w_profiles.svg'))

#%% Check on xy to uv mapping
from matplotlib.patches import Ellipse

frad = plt.figure(figsize=(6.5,8))
floc = plt.figure(figsize=(6.5,8))
for iR, label in enumerate(all_data.keys()):
    df = all_data[label]

    # recapitulate the fitting, which is a bit of overkill, but it gets us 
    # an accurate ellipse
    tgt_df = df[df['ctr-sur'] > 0]
    #tgt_df = df[df['scale_xy_dist'] <= 2]
    cov = np.cov(tgt_df['u'][df['scale_uv_dist'] < 2.2],
                 tgt_df['v'][df['scale_uv_dist'] < 2.2])
    com = (np.mean(tgt_df['u'][df['scale_uv_dist'] < 2.2]),
           np.mean(tgt_df['v'][df['scale_uv_dist'] < 2.2]))
    a = (cov[0,0] + cov[1,1])/2 + np.sqrt(((cov[0,0] - cov[1,1])/2)**2 + cov[0,1]**2)
    b = (cov[0,0] + cov[1,1])/2 - np.sqrt(((cov[0,0] - cov[1,1])/2)**2 + cov[0,1]**2)
    print('avg radius: %2.2f' %(2*(np.sqrt(a) + np.sqrt(b))/2))
    theta = np.arctan2(a - cov[0,0], cov[1,0])
    ellipse = Ellipse(com,
                      width=2*2*np.sqrt(a),
                      height=2*2*np.sqrt(b),
                      angle=180*theta/np.pi,
                      zorder=100, alpha=1., edgecolor='r', facecolor='None')
    # show localizer data
    minx = np.min(df['u'].values)
    miny = np.min(df['v'].values)
    ax = frad.add_subplot(np.ceil(len(datasets)/2),2,iR+1)
    
    # Plot the radius determined by the normalized uv coordinates (this should be in SD of a 2D Gaussian fitted to the loc data)
    cmap = plt.cm.get_cmap('viridis')
    pcm = ax.scatter(df['u'],df['v'],c=df['scale_uv_dist'],s=10,cmap=cmap)
    plt.colorbar(pcm,ax=ax)
    ax.add_patch(ellipse)
    ax.patch.set_facecolor('r')
    ax.set_title(label+" radius: SD<2 Nvox = %d" %(np.sum(df['scale_uv_dist']<2)),fontsize=6)
    ax.axis('off')
    
    # Plot the ctr-sur betas
    floc = plt.figure(floc)
    cmap_rev = cmap.reversed()
    plt.subplot(np.ceil(len(datasets)/2),2,iR+1)
    plt.scatter(df['u'],df['v'],c=df['ctr-sur'],s=10,cmap=cmap_rev)
    plt.colorbar()
    plt.title(label+" localizer",fontsize=6)
    plt.tight_layout(pad=0.1)
    
if savefigs:
    frad.savefig(os.path.join(figDir,'uv_map_rad.svg'))
    floc.savefig(os.path.join(figDir,'uv_map_loc.svg'))

#%% Histograms of p-values
floc = plt.figure()
for iR, label in enumerate(all_data.keys()):
    df = all_data[label]
    
    roi = df[df['scale_uv_dist'] < roiRad]
    if 'loc pval' in roi.keys():
        roi = roi.rename(columns={'loc pval':'loc p-val'})
    plt.subplot(np.ceil(len(datasets)/2),2,iR+1)
    plt.hist(roi['loc p-val'].values,bins=20,density=True)
    plt.title(label+" loc p-val",fontsize=8)
    plt.xlabel("pval")
    plt.text(0.8,5,'< 0.05 = %d %%' %(100*np.sum(roi['loc p-val'] <= 0.05)/len(roi['loc p-val'])))
    plt.ylim([0,10])
    plt.xlim([0,1])
floc.tight_layout(pad=0.1)

ftask = plt.figure()
for iR, label in enumerate(all_data.keys()):
    df = all_data[label]
    
    roi = df[df['scale_uv_dist'] < roiRad]
    if 'task pval' in roi.keys():
        roi = roi.rename(columns={'task pval':'task p-val'})
    plt.subplot(np.ceil(len(datasets)/2),2,iR+1)
    plt.hist(roi['task p-val'].values,bins=20,density=True)
    plt.title(label+" task p-val",fontsize=8)
    plt.xlabel("pval")
    plt.text(0.8,5,'< 0.05 = %d %%' %(100*np.sum(roi['task p-val'] <= 0.05)/len(roi['task p-val'])))
    plt.ylim([0,10])
    plt.xlim([0,1])
ftask.tight_layout(pad=0.1)

if savefigs:
    floc.savefig(os.path.join(figDir,'pvals_loc.svg'))
    ftask.savefig(os.path.join(figDir,'pvals_task.svg'))

#%% Depth Histograms
# I want to see how much coverage we are getting through depth.
roiRad = 2
fdhist = plt.figure(figsize=(15,4))
for iR, label in enumerate(all_data.keys()):
    df = all_data[label]
    
    roi = df[df['scale_uv_dist'] < roiRad]
    roi = df[df['scale_uv_dist'] < roiRad]
    if 'loc pval' in roi.keys():
        roi = roi.rename(columns={'loc pval':'loc p-val'})
    plt.subplot(2,np.ceil(len(datasets)/2),iR+1)
    plt.hist(roi['d'].values,bins=nDepths)
    plt.title(label)
    plt.xlabel("Normalize Depth WM -> GM")
    plt.ylabel("Num. Voxels")
    plt.legend(['N='+str(len(roi)),], fontsize = 6)
fdhist.tight_layout(pad=0.0)

if savefigs:
    fdhist.savefig(os.path.join(figDir,'depth_hist.svg'))
    
#%% Use the deepest layer as a proxy for non-vein contaminated voxels
# Then define the threshold based on this distribution

deep_pct = 10 #percentile to call deep layers
conditions = ['iso0','iso90','orth','sur']
depth_groups = {'deep': [0.2,0.4], 'middle': [0.4,0.6], 'superficial': [0.6,0.8]}
depth_labels = ['superficial','middle','deep'] #put them in the right order
depth_var = 'd'
x_var = 'u'
y_var = 'v'
sd_thresh = 2 #how many st. dev. of the deep layer mean to use as the threshold
mask_dict = {} #create a mask dictionary
lmnv_dict = {key:{'mean':0,'std':0,'thresh':0,'deep_mean':0,'deep_std':0} for key in all_data.keys()} #thresh dictionary
fsize=8 #fontsize of title
depth_groups = {'deep': [0.2,0.4], 'middle': [0.4,0.6], 'superficial': [0.6,0.8]}
depth_labels = ['superficial','middle','deep'] #put them in the right order
Ngroups = len(depth_groups.keys())
NROIs = len(all_data.keys())
for k_i, key in enumerate(all_data.keys()):

    # calculate log(MNV)
    df = all_data[key]
    lmnv = get_lmnv(df,key='task stdev_xerrts') #log of the mean-normalized variance
    mnv = np.exp(lmnv) #get back mean normalized variance
    
    # get deep layer distribution
    z = df[depth_var]
    [deep_mean, deep_std, deep] = get_deep_layer_dist(df,depth_var,deep_pct)
    lmnv_dict[key]['deep_mean'] = deep_mean
    lmnv_dict[key]['deep_std'] = deep_std
    
    # define threshold based on deep layer distribution
    [mnv_mask, lmnv_thresh] = get_mnv_mask(df,depth_var,deep_pct,sd_thresh)
    lmnv_dict[key]['thresh'] = lmnv_thresh
    lmnv_dict[key]['mean'] = np.mean(lmnv)
    lmnv_dict[key]['std'] = np.std(lmnv)
    mask_dict[key] = mnv_mask
    all_data[key]['no_vein'] = mnv_mask
    
    # Plot distributions
    fthresh = plot_mnv_histograms(lmnv, lmnv[deep], mnv_mask, deep_pct, key, k_i, NROIs, fsize, pad=0.0, figsize=(15,3))
    
    # Plot depth maps
    dmap = plot_depth_maps(df, depth_var, depth_groups, depth_labels, x_var, y_var, mnv, k_i, NROIs, [0,100], fsize, fname = 'dmap', pad=0.0)
        
    #plot thresholded map
    dmap_thresh = plot_depth_maps(df, depth_var, depth_groups, depth_labels, x_var, y_var, mnv, k_i, NROIs, [0, 100], fsize, fname='dmap_thresh', mask=mnv_mask, pad=0.0)
        
    # Plot voxel loss at each depth after masking
    fdepth_hist = plot_depth_voxel_loss(z, mnv_mask, nDepths, NROIs, key, k_i, fsize)
    
    #report number of voxels after threshold
    print("%d/%d Voxels Survive for %s" %(np.sum(mnv_mask),np.size(mnv),key))
    
if savefigs:
    fthresh.savefig(os.path.join(figDir,'mnv_hist.svg'))
    dmap.savefig(os.path.join(figDir,'mnv_depth_map.svg'))
    dmap_thresh.savefig(os.path.join(figDir,'mnv_depth_map_thresh.svg'))
    fdepth_hist.savefig(os.path.join(figDir,'mnv_depth_hist.svg'))

#%% Compare thresholds between subjects

f = plt.figure()
for k_i, key in enumerate(all_data.keys()):
    plt.errorbar(k_i,lmnv_dict[key]['mean'],lmnv_dict[key]['std'],color='b',linestyle='None',marker='o')
    plt.errorbar(k_i+0.1,lmnv_dict[key]['deep_mean'],lmnv_dict[key]['deep_std'],color='orange',linestyle='None',marker='o')
    plt.plot(k_i+0.2,lmnv_dict[key]['thresh'],color='r',marker='s')
plt.xticks(np.arange(0,len(all_data.keys())),all_data.keys(),rotation=15,fontsize=6)
plt.ylabel("log(MNV)")
#plt.legend(['full','thresh'])

if savefigs:
    f.savefig(os.path.join(figDir,'mnv_summary_errorbars.svg'))

#try violin plots
spreadF = 2
f = plt.figure()
for k_i, key in enumerate(all_data.keys()):
    df = all_data[key]
    lmnv = get_lmnv(df,key='task stdev_xerrts') #log of the mean-normalized variance
    [deep_mean, deep_std, deep] = get_deep_layer_dist(df,depth_var,deep_pct)
    violin_parts = plt.violinplot(lmnv,positions=[spreadF*k_i],showmedians=True)
    for pc in violin_parts['bodies']:
        pc.set_facecolor('b')
        pc.set_edgecolor('b')
    for pc in violin_parts:
        if not isinstance(violin_parts[pc],list):
            violin_parts[pc].set_edgecolor('b')
    violin_parts = plt.violinplot(lmnv[deep],positions=[spreadF*(k_i+0.2)],showmedians=True)
    for pc in violin_parts['bodies']:
        pc.set_facecolor('orange')
        pc.set_edgecolor('orange')
    for pc in violin_parts:
        if not isinstance(violin_parts[pc],list):
            violin_parts[pc].set_edgecolor('orange')
    plt.plot(spreadF*(k_i+0.4),lmnv_dict[key]['thresh'],color='r',marker='s')
plt.xticks(np.arange(0,spreadF*len(all_data.keys()),spreadF),all_data.keys(),rotation=15,fontsize=6)
plt.ylabel("log(MNV)")

if savefigs:
    f.savefig(os.path.join(figDir,'mnv_summary_violin.svg'))
    
#%% Apply full model p-val mask if desired

use_fullmodel_mask = True
pthresh_fullmodel = 0.05
if use_fullmodel_mask:
    for k_i, key in enumerate(all_data.keys()):
        df = all_data[key]
        pvals = df['task p-val']
        pval_mask = pvals < pthresh_fullmodel
        print("%d/%d voxels survive full model p-val mask" %(np.sum(pval_mask),np.size(pval_mask)))
        mask_dict[key] = mask_dict[key] & pval_mask   
        all_data[key]['sig'] = pval_mask

#%% Plot Depth Profiles
    
statDetails = {'labels': ['sur', 'iso0', 'iso90', 'orth', 'ctr', 'sur.1', 'ctr-sur'],
                'colors': [[.7, .7, .7], 'red', 'darkviolet', 'orange', 'gold', 'purple', 'coral']}
diffDetails = {}
diffDetails['statIDs'] = {'odss': ['orth','iso90'],
                          'fgm': ['iso90','iso0'],
                          'dsi': ['orth','iso0'],
                          'iso-sur': ['iso0','sur'],
                          'ctr-sur': ['ctr','sur.1']}
diffDetails['colors'] = ['green','magenta','cyan','black','coral']
profile_method = 'bin' # bin or smooth
roiRad = 2
#pick out ROIs where we're sure of localization
roi_dict = {}
for key in all_data.keys():
    df = all_data[key]
    roi_dict[key] = df['scale_uv_dist'] < roiRad
    all_data[key]['in_tgt'] = df['scale_uv_dist'] < roiRad

#%% Combine Hemis

roi_labels = list(all_data.keys())
subj_labels = [roi_labels[i][:6] for i in range(len(roi_labels))]
subj_data = {subj:{} for subj in subj_labels}
for subj in subj_labels:
    first_roi = True
    for roi in roi_labels:
        if (subj in roi) and first_roi:
            subj_data[subj] = all_data[roi]
            first_roi = False
        elif (subj in roi) and not first_roi:
            subj_data[subj] = pd.concat([subj_data[subj],all_data[roi]],ignore_index=True)
masks_subj = {subj:subj_data[subj]['in_tgt']*subj_data[subj]['sig']*subj_data[subj]['no_vein'] for subj in subj_labels}

useSI = False #use suppression index rather than differences (cond1 - cond2 / cond1 + cond2)
depthProfilesSubj = compute_all_depth_profiles(subj_data,statDetails,profile_method,nDepths,masks_subj,depthParam='d',radialParam='scale_uv_dist',spec_Drange='MinMax')
diffProfilesSubj = compute_diff_profiles(subj_data,statDetails,diffDetails['statIDs'],profile_method,nDepths,useSI,masks_subj,depthParam='d',radialParam='scale_uv_dist',spec_Drange='MinMax')

#plot centroids for each condition and ROI
plot_centroids(subj_data, masks_subj, statDetails, roiRad, nDepths)
        
#calculate difference profiles
plot_centroids_diff(subj_data, masks_subj, statDetails, diffDetails, roiRad, nDepths)

#save
if savefigs:
    for l in statDetails['labels']:
        plt.figure(l)
        plt.savefig(os.path.join(figDir,'centroids_%s_subj.svg' %l))
    for l in diffDetails['statIDs'].keys():
        plt.figure(l)
        plt.savefig(os.path.join(figDir,'centroids_%s_subj.svg' %l))
        
#%% Deconvolution

#reformat data to fit decon_rois specs
Nsubj = len(np.unique(subj_labels))
keep_subj = np.zeros((Nsubj,len(statDetails['labels']),nDepths))
for iR, subjID in enumerate(subj_data.keys()):
    for iStat, stat in enumerate(statDetails['labels']):
        keep_subj[iR,iStat,:] = depthProfilesSubj[stat]['avg'][iR]

#define point spread function
p2t_model = 6.2 #peak to tail ratio from Markuerkiaga et al. (2021) estimated for TE = 33.3 ms    
Nbins_model = 10 #number of bins used in the model from Markuerkiaga et al. (2021)
Nbins = nDepths #number of bins to use in this analysis

normalize_psf = False #True if you want to normalize the psf by the deepest layer  

decon_subj = depth_deconv(keep_subj,p2t_model,Nbins_model,Nbins,normalize_psf)

#now put back in dictionary
for iStat, stat in enumerate(statDetails['labels']):
    depthProfilesSubj[stat]['avg_decon'] = np.squeeze(np.array(decon_subj)[:,iStat,:])
    
#%% now make some average plots

prop_err = False # do error propagation?
use_decon = True
useSI = False

taskStats = statDetails['labels'][0:4]
taskColors = statDetails['colors'][0:4]
taskDiffs = list(diffDetails['statIDs'].keys())[0:4]
locStats = statDetails['labels'][4:]
locColors = statDetails['colors'][4:]
locDiffs = list(diffDetails['statIDs'].keys())[4:]

[avgTaskProfilesSubj, avgTaskDiffsSubj] = compute_avg_depth_profile(depthProfilesSubj,statDetails,diffDetails['statIDs'],taskStats,taskDiffs,use_decon,prop_err,useSI)  
[avgLocProfilesSubj, avgLocDiffsSubj] = compute_avg_depth_profile(depthProfilesSubj,statDetails,diffDetails['statIDs'],locStats,locDiffs,use_decon,prop_err,useSI)

# Plot task average profiles
fig = plt.figure(figsize=(6, 4))
fig.set_size_inches((6,4))
fig.patch.set_facecolor(fcolor)
    
fig.clf()
fsize = 14
    
p1 = fig.add_axes([.15, .2, .3, .7])
fix_axes(p1, lcolor=lcolor, fcolor=fcolor)

if use_decon:
    dx = 4.
    dy = .7
else:
    dx = 1.
    dy = .7

ylim = [-0.02,1.02]
xlim = [0,6]
Ntext = [4,0.05]
plot_avg_depth_profile(p1,avgTaskProfilesSubj,taskStats,taskColors,ylim,xlim,dx,dy,Ntext,lcolor,fsize)

p2 = fig.add_axes([.7, .2, .25, .7])
fix_axes(p2, lcolor=lcolor, fcolor=fcolor)
xlim = [-0.3,1.5]
plot_avg_diff_profile(p2,avgTaskDiffsSubj,taskDiffs,diffDetails['colors'],ylim,xlim,dx,dy,Ntext,lcolor,fsize,useSI)

# Plot loc average profiles
fig2 = plt.figure(figsize=(6, 4))
fig2.set_size_inches((6,4))
fig2.patch.set_facecolor(fcolor)
    
fig2.clf()
fsize = 14
    
p1 = fig2.add_axes([.15, .2, .3, .7])
fix_axes(p1, lcolor=lcolor, fcolor=fcolor)

if use_decon:
    dx = 4.
    dy = .7
else:
    dx = 1.
    dy = .7

ylim = [-0.02,1.02]
xlim = [-0.7,6]
Ntext = [4,0.05]
plot_avg_depth_profile(p1,avgLocProfilesSubj,locStats,locColors,ylim,xlim,dx,dy,Ntext,lcolor,fsize)

p2 = fig2.add_axes([.7, .2, .25, .7])
fix_axes(p2, lcolor=lcolor, fcolor=fcolor)
xlim = [-0.3,1.5]
    
plot_avg_diff_profile(p2,avgLocDiffsSubj,locDiffs,diffDetails['colors'][4:],ylim,xlim,dx,dy,Ntext,lcolor,fsize,useSI)


if savefigs:
    fig.savefig(os.path.join(figDir,'avg_profiles_task_subj.svg'))
    fig2.savefig(os.path.join(figDir,'avg_profiles_loc_subj.svg'))
    
#%% Plot each context modulation effect separately

pthresh = 0.05 #pvalue significance threshold

#iso and surround only
fig = plt.figure(figsize=(6, 4))
fig.set_size_inches((6,4))
fig.patch.set_facecolor(fcolor)

fig.clf()
fsize = 14

p1 = fig.add_axes([.15, .2, .3, .7])
fix_axes(p1, lcolor=lcolor, fcolor=fcolor)

ylim = [-0.02,1.02]
xlim = [0,6]
Ntext = [4,0.05]
plot_avg_depth_profile(p1,avgTaskProfilesSubj,['sur','iso0'],[[0.7,0.7,0.7],'red'],ylim,xlim,dx,dy,Ntext,lcolor,fsize)

#iso-sur
xlim = [-0.8,1.5]
p2 = fig.add_axes([.7, .2, .25, .7])
fix_axes(p2, lcolor=lcolor, fcolor=fcolor)
plot_avg_diff_profile(p2,avgTaskDiffsSubj,['iso-sur'],['black'],ylim,xlim,dx,dy,Ntext,lcolor,fsize,useSI,showSig=True,pthresh=pthresh,statCorrType='bonferroni')

if savefigs:
    fig.savefig(os.path.join(figDir,'avg_subj_profiles_iso_sur.svg'))

#iso and orth
fig = plt.figure(figsize=(6, 4))
fig.set_size_inches((6,4))
fig.patch.set_facecolor(fcolor)

fig.clf()
fsize = 14

p1 = fig.add_axes([.15, .2, .3, .7])
fix_axes(p1, lcolor=lcolor, fcolor=fcolor)

ylim = [-0.02,1.02]
xlim = [0,6]
Ntext = [4,0.05]
plot_avg_depth_profile(p1,avgTaskProfilesSubj,['iso0','orth'],['red','orange'],ylim,xlim,dx,dy,Ntext,lcolor,fsize)

#dSI
xlim = [-0.8,1.5]
p2 = fig.add_axes([.7, .2, .25, .7])
fix_axes(p2, lcolor=lcolor, fcolor=fcolor)
plot_avg_diff_profile(p2,avgTaskDiffsSubj,['dsi'],['tab:cyan'],ylim,xlim,dx,dy,Ntext,lcolor,fsize,useSI,showSig=True,pthresh=pthresh,statCorrType='bonferroni')

if savefigs:
    fig.savefig(os.path.join(figDir,'avg_subj_profiles_dsi.svg'))

#iso and iso90
fig = plt.figure(figsize=(6, 4))
fig.set_size_inches((6,4))
fig.patch.set_facecolor(fcolor)

fig.clf()
fsize = 14

p1 = fig.add_axes([.15, .2, .3, .7])
fix_axes(p1, lcolor=lcolor, fcolor=fcolor)

ylim = [-0.02,1.02]
xlim = [0,6]
Ntext = [4,0.05]
plot_avg_depth_profile(p1,avgTaskProfilesSubj,['iso0','iso90'],['red','darkviolet'],ylim,xlim,dx,dy,Ntext,lcolor,fsize)

#FGM
xlim = [-0.8,1.5]
p2 = fig.add_axes([.7, .2, .25, .7])
fix_axes(p2, lcolor=lcolor, fcolor=fcolor)
plot_avg_diff_profile(p2,avgTaskDiffsSubj,['fgm'],['magenta'],ylim,xlim,dx,dy,Ntext,lcolor,fsize,useSI,showSig=True,pthresh=pthresh,statCorrType='bonferroni')

if savefigs:
    fig.savefig(os.path.join(figDir,'avg_subj_profiles_fgm.svg'))

#iso90 and orth    
fig = plt.figure(figsize=(6, 4))
fig.set_size_inches((6,4))
fig.patch.set_facecolor(fcolor)

fig.clf()
fsize = 14

p1 = fig.add_axes([.15, .2, .3, .7])
fix_axes(p1, lcolor=lcolor, fcolor=fcolor)
    
ylim = [-0.02,1.02]
xlim = [0,6]
Ntext = [4,0.05]
plot_avg_depth_profile(p1,avgTaskProfilesSubj,['iso90','orth'],['purple','orange'],ylim,xlim,dx,dy,Ntext,lcolor,fsize)

#OTSS
xlim = [-0.8,1.5]
p2 = fig.add_axes([.7, .2, .25, .7])
fix_axes(p2, lcolor=lcolor, fcolor=fcolor)
plot_avg_diff_profile(p2,avgTaskDiffsSubj,['odss'],['tab:green'],ylim,xlim,dx,dy,Ntext,lcolor,fsize,useSI,showSig=True,pthresh=pthresh,statCorrType='bonferroni')

if savefigs:
    fig.savefig(os.path.join(figDir,'avg_subj_profiles_otss.svg'))

#ctr and sur
fig = plt.figure(figsize=(6, 4))
fig.set_size_inches((6,4))
fig.patch.set_facecolor(fcolor)
    
fig.clf()
fsize = 14

p1 = fig.add_axes([.15, .2, .3, .7])
fix_axes(p1, lcolor=lcolor, fcolor=fcolor)
    
ylim = [-0.02,1.02]
xlim = [-1,6]
Ntext = [4,0.05]
plot_avg_depth_profile(p1,avgLocProfilesSubj,['ctr','sur.1'],['gold','purple'],ylim,xlim,dx,dy,Ntext,lcolor,fsize)

#ctr - sur
xlim = [-0.8,1.5]
p2 = fig.add_axes([.7, .2, .25, .7])
fix_axes(p2, lcolor=lcolor, fcolor=fcolor)
plot_avg_diff_profile(p2,avgLocDiffsSubj,['ctr-sur'],['coral'],ylim,xlim,dx,dy,Ntext,lcolor,fsize,useSI,showSig=True,pthresh=pthresh,statCorrType='bonferroni')


if savefigs:
    fig.savefig(os.path.join(figDir,'avg_subj_profiles_ctr_sur.svg'))
    
#%% Make condition depth profiles with individual subject data overlaid

fig = plt.figure(figsize=(6, 4))
fig.set_size_inches((6,4))
fig.patch.set_facecolor(fcolor)

fig.clf()
fsize = 14

p1 = fig.add_axes([.15, .2, .3, .7])
fix_axes(p1, lcolor=lcolor, fcolor=fcolor)
    
ylim = [-0.02,1.02]
xlim = [0,6]
Ntext = [4,0.05]
plot_avg_depth_profile(p1,avgTaskProfilesSubj,['sur'],['gray'],ylim,xlim,dx,dy,Ntext,lcolor,fsize,plot_indiv=depthProfilesSubj)

if savefigs:
    fig.savefig(os.path.join(figDir,'avg_subj_profiles_sur.svg'))

fig = plt.figure(figsize=(6, 4))
fig.set_size_inches((6,4))
fig.patch.set_facecolor(fcolor)

fig.clf()
fsize = 14

p1 = fig.add_axes([.15, .2, .3, .7])
fix_axes(p1, lcolor=lcolor, fcolor=fcolor)
    
ylim = [-0.02,1.02]
xlim = [0,6]
Ntext = [4,0.05]
plot_avg_depth_profile(p1,avgTaskProfilesSubj,['iso0'],['red'],ylim,xlim,dx,dy,Ntext,lcolor,fsize,plot_indiv=depthProfilesSubj)

if savefigs:
    fig.savefig(os.path.join(figDir,'avg_subj_profiles_iso0.svg'))

fig = plt.figure(figsize=(6, 4))
fig.set_size_inches((6,4))
fig.patch.set_facecolor(fcolor)

fig.clf()
fsize = 14

p1 = fig.add_axes([.15, .2, .3, .7])
fix_axes(p1, lcolor=lcolor, fcolor=fcolor)
    
ylim = [-0.02,1.02]
xlim = [0,6]
Ntext = [4,0.05]
plot_avg_depth_profile(p1,avgTaskProfilesSubj,['iso90'],['darkviolet'],ylim,xlim,dx,dy,Ntext,lcolor,fsize,plot_indiv=depthProfilesSubj)

if savefigs:
    fig.savefig(os.path.join(figDir,'avg_subj_profiles_iso90.svg'))

fig = plt.figure(figsize=(6, 4))
fig.set_size_inches((6,4))
fig.patch.set_facecolor(fcolor)

fig.clf()
fsize = 14

p1 = fig.add_axes([.15, .2, .3, .7])
fix_axes(p1, lcolor=lcolor, fcolor=fcolor)
    
ylim = [-0.02,1.02]
xlim = [0,6]
Ntext = [4,0.05]
plot_avg_depth_profile(p1,avgTaskProfilesSubj,['orth'],['orange'],ylim,xlim,dx,dy,Ntext,lcolor,fsize,plot_indiv=depthProfilesSubj)

if savefigs:
    fig.savefig(os.path.join(figDir,'avg_subj_profiles_orth.svg'))
    
fig = plt.figure(figsize=(6, 4))
fig.set_size_inches((6,4))
fig.patch.set_facecolor(fcolor)

fig.clf()
fsize = 14

p1 = fig.add_axes([.15, .2, .3, .7])
fix_axes(p1, lcolor=lcolor, fcolor=fcolor)
    
ylim = [-0.02,1.02]
xlim = [-2.2,6]
Ntext = [4,0.05]
plot_avg_depth_profile(p1,avgLocProfilesSubj,['ctr'],['gold'],ylim,xlim,dx,dy,Ntext,lcolor,fsize,plot_indiv=depthProfilesSubj)

if savefigs:
    fig.savefig(os.path.join(figDir,'avg_subj_profiles_ctr.svg'))
    
fig = plt.figure(figsize=(6, 4))
fig.set_size_inches((6,4))
fig.patch.set_facecolor(fcolor)

fig.clf()
fsize = 14

p1 = fig.add_axes([.15, .2, .3, .7])
fix_axes(p1, lcolor=lcolor, fcolor=fcolor)
    
ylim = [-0.02,1.02]
xlim = [-2.2,6]
Ntext = [4,0.05]
plot_avg_depth_profile(p1,avgLocProfilesSubj,['sur.1'],['purple'],ylim,xlim,dx,dy,Ntext,lcolor,fsize,plot_indiv=depthProfilesSubj)

if savefigs:
    fig.savefig(os.path.join(figDir,'avg_subj_profiles_sur1.svg'))
